/*
 * Sandwood
 *
 * Copyright (c) 2019-2023, Oracle and/or its affiliates
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
 */

package org.sandwood.runtime.model.variables;

import org.sandwood.runtime.model.RetentionPolicy;

/**
 * An interface that is implemented by all objects that represent values that are computed as the model executes.
 */
public interface ComputedVariable extends HasProbability, Variable {

    /**
     * An Enumeration to describe the current state of the variable
     *
     */
    enum Immutability {
        /**
         * This value can change freely
         */
        FREE,
        /**
         * This value is fixed in the state generated by sampling.
         */
        FIXED,
        /**
         * Some of the sampled values that are composed to make this value are fixed.
         */
        PARTIALLY_FIXED,
        /**
         * This value is always the same in the model. For example the sum of two constants.
         */
        DETERMINISTIC
    }

    /**
     * Has the model been run so that calling get on this variable is a valid action.
     * 
     * @return A boolean showing if the model has been set.
     */
    boolean isSet();

    /**
     * A method to set the retention policy of this variable.
     * 
     * @param p The retention policy this variable is to be set to.
     */
    void setRetentionPolicy(RetentionPolicy p);

    /**
     * Method to query the retention policy of this variable.
     * 
     * @return The retention policy this variable is currently set to.
     */
    RetentionPolicy getRetentionPolicy();

    /**
     * Method to fix and unfix the value in the model represented by this object.
     * 
     * @param fixed If true the parameter is fixed, if false the parameter is free to be modified.
     */
    void setFixed(boolean fixed);

    /**
     * Method to test if this variable is fixed
     * 
     * @return Is the value fixed?
     */
    Immutability isFixed();
}