package org.sandwood.compiler.tests.parser;

interface HMMMetrics4$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public double[][] get$current_metric_mean();
	public void set$current_metric_mean(double[][] cv$value);
	public double[][] get$current_metric_valid_bias();
	public void set$current_metric_valid_bias(double[][] cv$value);
	public double[][] get$current_metric_var();
	public void set$current_metric_var(double[][] cv$value);
	public boolean get$fixedFlag$sample134();
	public void set$fixedFlag$sample134(boolean cv$value);
	public boolean get$fixedFlag$sample162();
	public void set$fixedFlag$sample162(boolean cv$value);
	public boolean get$fixedFlag$sample190();
	public void set$fixedFlag$sample190(boolean cv$value);
	public boolean get$fixedFlag$sample20();
	public void set$fixedFlag$sample20(boolean cv$value);
	public boolean get$fixedFlag$sample256();
	public void set$fixedFlag$sample256(boolean cv$value);
	public boolean get$fixedFlag$sample33();
	public void set$fixedFlag$sample33(boolean cv$value);
	public boolean get$fixedFlag$sample57();
	public void set$fixedFlag$sample57(boolean cv$value);
	public boolean get$fixedFlag$sample76();
	public void set$fixedFlag$sample76(boolean cv$value);
	public double[] get$initialStateDistribution();
	public void set$initialStateDistribution(double[] cv$value);
	public int[][] get$length$metric();
	public void set$length$metric(int[][] cv$value);
	public double get$logProbability$current_metric_mean();
	public double get$logProbability$current_metric_valid_bias();
	public double get$logProbability$current_metric_var();
	public double get$logProbability$initialStateDistribution();
	public double get$logProbability$m();
	public double get$logProbability$metric_g();
	public double get$logProbability$metric_valid_g();
	public double get$logProbability$st();
	public double[][] get$m();
	public void set$m(double[][] cv$value);
	public int get$max_metric();
	public void set$max_metric(int cv$value);
	public double[][][] get$metric();
	public void set$metric(double[][][] cv$value);
	public double[][][] get$metric_g();
	public boolean[][][] get$metric_valid();
	public void set$metric_valid(boolean[][][] cv$value);
	public boolean[][][] get$metric_valid_g();
	public int get$noSamples();
	public int get$noServers();
	public int get$noStates();
	public void set$noStates(int cv$value);
	public int[][] get$st();
	public void set$st(int[][] cv$value);
	public double[] get$v();
	public void logEvidenceGeneration();
}