package org.sandwood.compiler.tests.parser;

interface TerminalVariables$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public double[][][][][] get$a();
	public int get$c1();
	public void set$c1(int cv$value, boolean allocated$);
	public int get$c10();
	public void set$c10(int cv$value, boolean allocated$);
	public int get$c11();
	public void set$c11(int cv$value, boolean allocated$);
	public int get$c12();
	public void set$c12(int cv$value, boolean allocated$);
	public int get$c2();
	public int get$c3();
	public void set$c3(int cv$value, boolean allocated$);
	public int get$c4();
	public void set$c4(int cv$value, boolean allocated$);
	public int get$c5();
	public void set$c5(int cv$value, boolean allocated$);
	public int get$c6();
	public void set$c6(int cv$value, boolean allocated$);
	public int get$c7();
	public void set$c7(int cv$value, boolean allocated$);
	public int get$c8();
	public void set$c8(int cv$value, boolean allocated$);
	public int get$c9();
	public void set$c9(int cv$value, boolean allocated$);
	public double[][] get$conditionals();
	public int get$evidence();
	public void set$evidence(int cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample47();
	public void set$fixedFlag$sample47(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample52();
	public void set$fixedFlag$sample52(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample55();
	public void set$fixedFlag$sample55(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample57();
	public void set$fixedFlag$sample57(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample60();
	public void set$fixedFlag$sample60(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample62();
	public void set$fixedFlag$sample62(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample636();
	public void set$fixedFlag$sample636(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample65();
	public void set$fixedFlag$sample65(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample67();
	public void set$fixedFlag$sample67(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample70();
	public void set$fixedFlag$sample70(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample72();
	public void set$fixedFlag$sample72(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample75();
	public void set$fixedFlag$sample75(boolean cv$value, boolean allocated$);
	public double get$logProbability$c1();
	public double get$logProbability$c10();
	public double get$logProbability$c11();
	public double get$logProbability$c12();
	public double get$logProbability$c2();
	public double get$logProbability$c3();
	public double get$logProbability$c4();
	public double get$logProbability$c5();
	public double get$logProbability$c6();
	public double get$logProbability$c7();
	public double get$logProbability$c8();
	public double get$logProbability$c9();
	public double get$logProbability$terminalVariable();
	public double[] get$priors();
	public int get$terminalVariable();
	public void set$terminalVariable(int cv$value, boolean allocated$);
}