/*
 * Sandwood
 *
 * Copyright (c) 2019-2025, Oracle and/or its affiliates
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
 */

package org.sandwood.compiler.traces.guards;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.PriorityQueue;
import java.util.Set;
import java.util.Stack;

import org.sandwood.compiler.compilation.CompilationContext;
import org.sandwood.compiler.compilation.scopesState.ScopeState.InitializedState;
import org.sandwood.compiler.dataflowGraph.scopes.BlockScope;
import org.sandwood.compiler.dataflowGraph.scopes.CommentScope;
import org.sandwood.compiler.dataflowGraph.scopes.ElseScope;
import org.sandwood.compiler.dataflowGraph.scopes.GlobalScope;
import org.sandwood.compiler.dataflowGraph.scopes.IfScope;
import org.sandwood.compiler.dataflowGraph.scopes.ReductionScope;
import org.sandwood.compiler.dataflowGraph.scopes.Scope;
import org.sandwood.compiler.dataflowGraph.scopes.Scope.ScopeType;
import org.sandwood.compiler.dataflowGraph.tasks.DFType;
import org.sandwood.compiler.dataflowGraph.tasks.DataflowTask;
import org.sandwood.compiler.dataflowGraph.tasks.arrayTasks.GetTask;
import org.sandwood.compiler.dataflowGraph.tasks.arrayTasks.PutTask;
import org.sandwood.compiler.dataflowGraph.tasks.sandwoodOperators.ForTask;
import org.sandwood.compiler.dataflowGraph.tasks.sandwoodOperators.IfElseAssignmentTask;
import org.sandwood.compiler.dataflowGraph.tasks.sandwoodOperators.ReductionInput;
import org.sandwood.compiler.dataflowGraph.tasks.sandwoodOperators.ReductionReturnTask;
import org.sandwood.compiler.dataflowGraph.variables.LocalVariableDescription;
import org.sandwood.compiler.dataflowGraph.variables.Variable;
import org.sandwood.compiler.dataflowGraph.variables.auxillary.DataflowTaskArgDesc;
import org.sandwood.compiler.dataflowGraph.variables.scalarVariables.BooleanVariable;
import org.sandwood.compiler.dataflowGraph.variables.scalarVariables.IntVariable;
import org.sandwood.compiler.exceptions.CompilerException;
import org.sandwood.compiler.exceptions.MissingFeatureException;
import org.sandwood.compiler.exceptions.SandwoodModelException;
import org.sandwood.compiler.names.VariableNames;
import org.sandwood.compiler.traces.Trace;
import org.sandwood.compiler.traces.TraceHandle;
import org.sandwood.compiler.traces.guards.ScopeConstructor.Values;
import org.sandwood.compiler.trees.Tree;
import org.sandwood.compiler.trees.irTree.IRTree;
import org.sandwood.compiler.trees.irTree.IRTreeReturn;
import org.sandwood.compiler.trees.irTree.IRTreeVoid;

public class TraceArrayRestrictions {

    /**
     * A comparator for comparing scopes.
     */
    private static final Comparator<Scope> scopeCmp = new Comparator<Scope>() {
        @Override
        public int compare(Scope s1, Scope s2) {
            return s1.id() - s2.id();
        }
    };

    /**
     * Class to record the scopes that we should add and remove when we reach this dataflow task;
     */
    private static class ScopeChanges {
        /**
         * Set containing the scopes to construct.
         */
        private final Set<Scope> toConstruct = new HashSet<>();

        /**
         * A set of for loops whose indexes are used by this task.
         */
        private final Set<ForTask> toUse = new HashSet<>();

        /**
         * A set of scopes that are already constructed for the end point of the trace and should be added to the
         * substitutions at this time, so that this and future tasks make use of them.
         */
        private final Set<Scope> toSubstitute = new HashSet<>();

        public void addConstructScopes(Collection<Scope> scopes) {
            toConstruct.addAll(scopes);
        }

        public void addUseScopes(Collection<ForTask> scopes) {
            toUse.addAll(scopes);
        }

        public void addToSubstitute(Scope s) {
            toSubstitute.add(s);
        }

        public Set<Scope> getConstructScopes() {
            return toConstruct;
        }

        public Set<Scope> getSubstituteScopes() {
            return toSubstitute;
        }

        @Override
        public String toString() {
            return "To Construct: " + toConstruct + "\nTo Use: " + toUse + "\n";
        }
    }

    private static class RestrictionsData {
        /**
         * A map from a dataflow task to the set of scopes that need to be duplicated to correctly handle this task.
         */
        final Map<DataflowTask<?>, ScopeChanges> scopeData = new HashMap<>();

        /**
         * A local id used to keep variable names distinct.
         */
        int localID = 1;

        /**
         * A global id to keep all the id's generated by this instance distinct from the id's generated by other
         * instances.
         */
        final int globalID;

        /**
         * A list of scopes to construct once the trace is constructed
         */
        final List<Scope> finalScopes = new ArrayList<>();

        /**
         * A set containing all the put tasks that are paired.
         */
        final Map<PutTask<?>, DataflowTask<?>> usedPuts = new HashMap<>();

        /**
         * The trace that this restriction is for.
         */
        final TraceHandle trace;

        /**
         * The preconstructed scopes for the start of the trace
         */
        final Map<Scope, IntVariable> existingStartScopes;

        /**
         * The preconstructed scopes for the end of the trace;
         */
        final Map<Scope, IntVariable> existingEndScopes;

        /**
         * Set of all the reduction inputs that consume an array that have been seen so far.
         */
        final Set<ReductionInput<?>> reductionInputs;

        /**
         * A set to record all put tasks that substitutions should be saved at.
         */
        final Set<PutTask<?>> storeSubstitutions = new HashSet<>();

        /**
         * A map from dataflow task to the set of variables that should be created when that task is reached.
         */
        final Map<DataflowTask<?>, Set<Variable<?>>> requiredVariables = new HashMap<>();

        /**
         * Should values that are constructed in this trace be passed down the trace.
         */
        final boolean passValues;

        /**
         * The initialisation state of variables in the final scopes if any final scopes have been created.
         */
        final InitializedState finalInitializationState;

        /**
         * A set containing all the scopes encompassing the final task in the trace.
         */
        final Set<Scope> allFinalScopes = new HashSet<>();

        /**
         * The position in the scope description that is being updated. TODO, determine if this is always the most
         * recent position. I think it might be.
         */
        final int position;

        /**
         *
         * @param trace
         * @param existingStartScopes
         * @param existingEndScopes
         * @param existingScopes
         * @param globalID
         */

        public RestrictionsData(int position, TraceHandle trace, Map<Scope, IntVariable> existingStartScopes,
                Map<Scope, IntVariable> existingEndScopes, Set<Scope> existingScopes,
                Set<ReductionInput<?>> reductionInputs, InitializedState finalInitializationState, int globalID,
                Values arrayValues) {
            this.position = position;
            this.trace = trace;
            this.existingStartScopes = Collections.unmodifiableMap(existingStartScopes);
            this.existingEndScopes = Collections.unmodifiableMap(existingEndScopes);
            this.reductionInputs = new HashSet<>(reductionInputs);
            this.finalInitializationState = finalInitializationState;
            this.globalID = globalID;
            passValues = arrayValues == Values.PASS_VALUES;
        }
    }

    /**
     *
     * @param trace               The trace that the restrictions should be built for
     * @param existingStartScopes A Mapping from the set of scopes that are already constructed for the first element in
     *                            the trace to the scope and index value used to represent this. The key values are
     *                            always scopes from the DAG, but because multiple instances of each scope maybe
     *                            constructed as restrictions are instantiated the corresponding value pairs may not be
     *                            the original scope values.
     * @param existingEndScopes   A Mapping from the set of scopes that are already constructed for the last element in
     *                            the trace to the scope and index value used to represent this. The key values are
     *                            always scopes from the DAG, but because multiple instances of each scope maybe
     *                            constructed as restrictions are instantiated the corresponding value pairs may not be
     *                            the original scope values.
     * @param target              The distribution description to build these constraints within.
     * @param globalID            An id from which this method can construct unique ids to ensure there are no name
     *                            conflicts.
     * @param passValues          A flag to mark if sampled values should be passed through so that if the trace is
     *                            valid the value at the start of it is available at the end.
     * @param position            The position within the distribution description that any new substitutions should be
     *                            placed in.
     * @param compilationCtx      The compilation context that holds the details of the compilation.
     *
     * @return A new distribution description that represents the original distribution with the constraints of the
     *         trace added.
     */
    // Scopes that are already constructed at the end are not included as the trees that are placed into them may not be
    // valid further out.
    public static ScopeDescription constructRestriction(TraceHandle trace, Map<Scope, IntVariable> existingStartScopes,
            Map<Scope, IntVariable> existingEndScopes, InitializedState finalInitializationState,
            ScopeDescription target, int globalID, Values arrayValues, int position,
            CompilationContext compilationCtx) {
        Set<TraceHandle> rawTraces = new HashSet<>();
        rawTraces.add(trace);
        return constructRestriction(trace, rawTraces, existingStartScopes, existingEndScopes, finalInitializationState,
                target, globalID, arrayValues, position, compilationCtx);
    }

    public static ScopeDescription constructRestriction(TraceHandle trace, Set<TraceHandle> rawTraces,
            Map<Scope, IntVariable> existingStartScopes, Map<Scope, IntVariable> existingEndScopes,
            InitializedState finalInitializationState, ScopeDescription target, int globalID, Values arrayValues,
            int position, CompilationContext compilationCtx) {
        RestrictionsData data = new RestrictionsData(position, trace, existingStartScopes, existingEndScopes,
                target.existingScopes, target.reductionInputs, finalInitializationState, globalID, arrayValues);

        constructOpPairs(data);

        for(TraceHandle t:rawTraces)
            getRequiredVariables(data, t, compilationCtx);

        if(position != 0) // No trace is set for zero as this is the initial scope constructor.
            getSubstitutionPoints(data, target.getTrace(position));

        getScopeRequirements(data);

        return constructRestrictionInternal(data, target, compilationCtx);
    }

    /**
     * A method for calculating which put tasks should result in an update to the overall substitutions of the scope
     * description when setting substitutions for back traces. In short only put tasks that appeared as part of the
     * original trace should be used for this. TODO this will fail if the constraint trace is simplified and the source
     * trace is not. By construction this should not occur, but add a test to ensure that thus never occurs.
     *
     * @param data
     * @param h
     */
    private static void getSubstitutionPoints(RestrictionsData data, TraceHandle h) {
        Trace sourceTrace = h.getTrace();
        Trace constraintTrace = data.trace.getTrace();
        /*
         * Remove the first element as it will always be recorded at the end, so does not need to be recorded here.
         * Break if the traces have diverged.
         */
        DataflowTaskArgDesc d = constraintTrace.pop();
        if(!d.equals(sourceTrace.pop()))
            return;

        while(!constraintTrace.isEmpty()) {
            d = constraintTrace.pop();
            switch(d.task.getType()) {
                case GET:
                case IF_ASSIGNMENT:
                case REDUCE_INPUT:
                    if(sourceTrace.isEmpty() || !d.equals(sourceTrace.pop()))
                        return;
                    break;
                case PUT:
                    if(sourceTrace.isEmpty())
                        return;
                    else {
                        DataflowTaskArgDesc sd = sourceTrace.pop();
                        if(!d.task.equals(sd.task))
                            return;
                        // TODO there may be issues here if the same task is met on a distribution trace, but in a
                        // different iteration, and then back tracking is used on the trace. Make sure that there are
                        // sufficient guards to prevent this.
                        data.storeSubstitutions.add((PutTask<?>) d.task);
                        if(d.argPos != sd.argPos)
                            return;
                    }
                    break;
                default:
                    if(sourceTrace.isEmpty())
                        return;
                    if(d.equals(sourceTrace.peek()))
                        sourceTrace.pop();
            }
        }
    }

    // A method to generate all the pairings of ops that need to have their indexes
    // compared.
    private static void constructOpPairs(RestrictionsData data) {
        // Get a copy of the trace.
        Trace trace = data.trace.getTrace();
        // Construct a stack that will hold all the gets that access elements from an
        // array on our trace.
        // The top element in this stack will always pair with a put when it is
        // encountered added an element
        // to an array.
        Stack<DataflowTask<?>> consumers = new Stack<>();
        // While there are elements left in the trace.
        while(!trace.isEmpty()) {
            // Get an element
            DataflowTaskArgDesc d = trace.pop();
            // Determine its type.
            switch(d.task.getType()) {
                // if it is a get and the array it is accessing is
                // in the trace push the get onto the stack.
                case GET:
                    if(d.argPos == 0)
                        consumers.push(d.task);
                    break;
                // If it is a put and the put is not just being passed by (argPos!=0)
                // recover the corresponding get, construct a pairing and populate the
                // scope data.
                case PUT:
                    assert (d.argPos != 0);
                    if(!consumers.isEmpty())
                        data.usedPuts.put((PutTask<?>) d.task, consumers.pop());
                    break;
                case REDUCE_INPUT:
                    if(d.argPos == 3)
                        consumers.push(d.task);
                    break;
                default:
                    break;
            }
        }
    }

    private static void getScopeRequirements(RestrictionsData data) {
        TraceHandle traceHandle = data.trace;

        int size = traceHandle.size();

        Set<Scope> existingStartScope = new HashSet<>(data.existingStartScopes.keySet());
        {
            Set<Scope> existingPutScopes = new HashSet<>(existingStartScope);
            Set<Scope> existingGetScopes = new HashSet<>(existingStartScope);

            for(int i = 0; i < size; i++) {
                DataflowTaskArgDesc d = traceHandle.get(i);
                switch(d.task.getType()) {
                    case GET: {
                        if(d.argPos == 0) {
                            GetTask<?> gt = (GetTask<?>) d.task;

                            // Construct an object to hold the scopes for this task and add it to the map
                            ScopeChanges s = new ScopeChanges();
                            data.scopeData.put(gt, s);

                            // Calculated the scopes used by this index.
                            Set<Scope> requiredScopes = new HashSet<>();
                            Set<ForTask> indexLoops = getRequiredLoops(gt.index);
                            indexLoops.addAll(getGuardScopes(gt.scope(), requiredScopes));
                            requiredScopes.addAll(indexLoops);

                            // Add the required scopes to set of used scopes
                            s.addUseScopes(indexLoops);

                            // Remove all the loops that are already constructed.
                            requiredScopes.removeAll(existingGetScopes);
                            s.addConstructScopes(requiredScopes);

                            // remove no longer available start scopes.
                            Set<Scope> newStartScope = new HashSet<>();
                            for(Scope scope:existingStartScope)
                                if(existingGetScopes.contains(scope))
                                    newStartScope.add(scope);
                            existingStartScope = newStartScope;

                            // update the set of put scope removing any that are
                            // not in the scope of the array as these could have
                            // changed since the last put.
                            Set<Scope> newPutScopes = new HashSet<>();
                            Scope vScope = gt.array.scope();
                            while(GlobalScope.scope != vScope) {
                                if(existingPutScopes.contains(vScope))
                                    newPutScopes.add(vScope);
                                vScope = vScope.getEnclosingScope();
                            }
                            existingPutScopes = newPutScopes;

                            // Update the running state
                            existingGetScopes.addAll(requiredScopes);
                            existingPutScopes.addAll(requiredScopes);
                        }
                        break;
                    }
                    case REDUCE_INPUT: {
                        ReductionInput<?> ri = (ReductionInput<?>) d.task;

                        // Construct an object to hold the scopes for this task and add it to the map
                        ScopeChanges s = new ScopeChanges();
                        data.scopeData.put(ri, s);

                        // Calculated the scopes used by this input.
                        Set<Scope> requiredScopes = new HashSet<>();
                        Set<ForTask> indexScopes = getRequiredLoops(ri.start);
                        indexScopes.addAll(getRequiredLoops(ri.end));
                        indexScopes.addAll(getGuardScopes(ri.scope(), requiredScopes));
                        requiredScopes.addAll(indexScopes);

                        // Add the required scopes to set of used scopes
                        s.addUseScopes(indexScopes);

                        // Remove all the scopes that are already constructed.
                        requiredScopes.removeAll(existingGetScopes);
                        s.addConstructScopes(requiredScopes);

                        // remove no longer available start scopes.
                        Set<Scope> newStartLoops = new HashSet<>();
                        for(Scope scope:existingStartScope)
                            if(existingGetScopes.contains(scope))
                                newStartLoops.add(scope);
                        existingStartScope = newStartLoops;

                        // update the set of put loops removing any that are
                        // not in the scope of the array as these could have
                        // changed since the last put.
                        Set<Scope> newPutScopes = new HashSet<>();
                        Scope vScope = ri.array.scope();
                        while(GlobalScope.scope != vScope) {
                            if(existingPutScopes.contains(vScope))
                                newPutScopes.add(vScope);
                            vScope = vScope.getEnclosingScope();
                        }
                        existingPutScopes = newPutScopes;

                        // Update the running state
                        existingGetScopes.addAll(requiredScopes);
                        existingPutScopes.addAll(requiredScopes);
                        break;
                    }

                    case PUT: {
                        assert (d.argPos != 0);
                        PutTask<?> pt = (PutTask<?>) d.task;

                        // Moving between scopes only happens with a put get/reduce pairing, if there is no
                        // corresponding get or reduce the trace cannot move between scopes.
                        // The value will be the get task for a get and null for a reduction.
                        DataflowTask<?> t = data.usedPuts.get(pt);
                        if(t != null) {
                            // Construct an object to hold the scopes for this task and add it to the map
                            ScopeChanges s = new ScopeChanges();
                            data.scopeData.put(pt, s);

                            // Calculated the scopes used by this index.
                            Set<Scope> requiredScopes = new HashSet<>();
                            Set<ForTask> indexLoops = getRequiredLoops(pt.index);
                            indexLoops.addAll(getGuardScopes(pt.scope(), requiredScopes));
                            requiredScopes.addAll(indexLoops);

                            // Add the index scopes to set of used scopes
                            s.addUseScopes(indexLoops);

                            // Calculate the scopes for the value
                            Set<ForTask> valueLoops;
                            if(data.passValues && !pt.value.getType().isArray()) {
                                valueLoops = getRequiredLoops(pt.value);
                                valueLoops.removeAll(indexLoops);
                                s.addUseScopes(valueLoops);
                                requiredScopes.addAll(valueLoops);
                            }

                            // Remove existing scopes leaving only the scopes that need to be constructed.
                            requiredScopes.removeAll(existingPutScopes);

                            s.addConstructScopes(requiredScopes);
                            existingPutScopes.addAll(requiredScopes);

                            /*
                             * Remove from the current get scopes set all the scopes that the array is visible in as
                             * these scopes could have changed.
                             * 
                             * The put task has to include all the scopes that could be used by the get task as the only
                             * way to get data out of a loop is to place it in an array.
                             */
                            Scope scope = pt.array.scope();
                            Set<Scope> newGetScopes = new HashSet<>();
                            while(GlobalScope.scope != scope) {
                                if(requiredScopes.contains(scope) || existingGetScopes.contains(scope))
                                    newGetScopes.add(scope);
                                scope = scope.getEnclosingScope();
                            }
                            existingGetScopes = newGetScopes;
                        }
                        break;
                    }
                    case IF_ASSIGNMENT: {
                        IfElseAssignmentTask<?> ifElseTask = (IfElseAssignmentTask<?>) d.task;
                        ScopeChanges s = new ScopeChanges();
                        data.scopeData.put(ifElseTask, s);

                        Set<Scope> requiredScopes = new HashSet<>();
                        Set<ForTask> guardLoops = getRequiredLoops(ifElseTask.guard);
                        guardLoops.addAll(getGuardScopes(ifElseTask.scope(), requiredScopes));
                        requiredScopes.addAll(guardLoops);
                        s.addUseScopes(guardLoops);

                        requiredScopes.removeAll(existingPutScopes);
                        s.addConstructScopes(requiredScopes);
                        existingPutScopes.addAll(requiredScopes);
                        existingGetScopes.addAll(requiredScopes);

                        break;
                    }
                    default:
                        break;
                }
            }
        }

        // If we are moving to the fixed scopes, not away from them, the trace needs to
        // be evaluated in reverse to exclude the fixed scopes.
        Set<Scope> existingEndScopes = new HashSet<>(data.existingEndScopes.keySet());
        Set<Scope> endScopesInScope = new HashSet<>(existingEndScopes);

        // Get the set of scopes that should be constructed by the end.
        Set<Scope> constructEndScopes = new HashSet<>();
        if(!traceHandle.isEmpty()) {
            Scope s = traceHandle.peek().task.scope();
            while(s != null) {
                if(!existingEndScopes.contains(s)) {
                    switch(s.getScopeType()) {
                        case ELSE:
                        case FOR:
                        case IF:
                        case BLOCK:
                        case COMMENT:
                            constructEndScopes.add(s);
                            break;
                        case GLOBAL:
                        case REDUCE:
                            break;
                    }
                }
                data.allFinalScopes.add(s);
                s = s.getEnclosingScope();
            }
        }

        for(int i = size - 1; i >= 0; i--) {
            DataflowTaskArgDesc d = traceHandle.get(i);
            switch(d.task.getType()) {
                case GET:
                case IF_ASSIGNMENT:
                case REDUCE_INPUT: {
                    ScopeChanges s = data.scopeData.get(d.task);
                    if(s != null) {
                        // Remove from the construction and substitution any end scopes that
                        // have already been constructed.
                        for(Scope t:endScopesInScope) {
                            s.toConstruct.remove(t);
                            if(s.toUse.contains(t))
                                s.addToSubstitute(t);
                        }

                        // Remove constructed scopes from the set that need to be constructed.
                        constructEndScopes.removeAll(s.getConstructScopes());
                    }
                    break;
                }
                case PUT: {
                    assert (d.argPos != 0);
                    PutTask<?> pt = (PutTask<?>) d.task;
                    // Moving between scopes only happens with a put get pairing, if there is no
                    // corresponding get the trace cannot move between scopes.
                    if(data.usedPuts.containsKey(pt)) {
                        // Calculate all the scopes that are now out of scope as they may have changed.
                        // In practice this is the same as used scopes up to vScope because of the
                        // constraints on put indexes.
                        Set<Scope> outOfScopeScopess = new HashSet<>();
                        Scope vScope = pt.array.scope();
                        Scope ptScope = pt.scope();
                        while(ptScope != vScope) {
                            outOfScopeScopess.add(ptScope);
                            ptScope = ptScope.getEnclosingScope();
                        }

                        // Remove any scopes that are constructed but are not out of scope
                        ScopeChanges s = data.scopeData.get(d.task);
                        while(vScope != GlobalScope.scope) {
                            if(s.toConstruct.contains(vScope))
                                constructEndScopes.remove(vScope);
                            vScope = vScope.getEnclosingScope();
                        }

                        // Remove scopes that are used in an earlier iteration, as the
                        // value of the scope may have changed, so a new scope should
                        // now be created in the earlier steps.
                        endScopesInScope.removeAll(outOfScopeScopess);
                        // Versions of these scopes constructed after this point
                        // are not necessarily in the correct iteration, so duplicates
                        // need to be constructed, and this is where we mark this.
                        for(Scope t:outOfScopeScopess) {
                            if(constructEndScopes.contains(t)) {
                                constructEndScopes.remove(t);
                                data.finalScopes.add(t);
                            }
                        }
                    }
                    break;
                }
                default:
                    break;
            }
        }

        // Construct any end scopes that have not been constructed already.
        constructEndScopes.removeAll(existingStartScope);
        data.finalScopes.addAll(constructEndScopes);
        Collections.sort(data.finalScopes, scopeCmp);
    }

    private static Set<ForTask> getGuardScopes(Scope scope, Set<Scope> guardScopes) {
        Set<ForTask> toReturn = new HashSet<>();
        while(scope != GlobalScope.scope) {
            switch(scope.getScopeType()) {
                case ELSE: {
                    ElseScope elseScope = (ElseScope) scope;
                    toReturn.addAll(getRequiredLoops(elseScope.ifScope.guard));
                    guardScopes.add(scope);
                    break;
                }
                case IF: {
                    IfScope ifScope = (IfScope) scope;
                    toReturn.addAll(getRequiredLoops(ifScope.guard));
                    guardScopes.add(ifScope);
                    break;
                }
                default:
                    break;
            }
            scope = scope.getEnclosingScope();
        }
        return toReturn;
    }

    /**
     * A method to get the set of variables that are required to be generated for each from the trace for the correct
     * evaluation of either the put tasks, or the code inserted in to the finally created scope.
     * 
     * @param data        The restrictionData object into which the results should be stored.
     * @param traceHandle The trace to examine.
     */
    private static void getRequiredVariables(RestrictionsData data, TraceHandle traceHandle,
            CompilationContext compilationCtx) {
        Set<Variable<?>> requiredVariables = new HashSet<>();

        int size = traceHandle.size();
        for(int i = 0; i < size; i++) {
            DataflowTaskArgDesc d = traceHandle.get(i);
            switch(d.task.getType()) {
                case GET:
                case IF_ASSIGNMENT:
                    break;

                case PUT: {
                    PutTask<?> pt = (PutTask<?>) d.task;
                    if(data.usedPuts.containsKey(pt)) { // Data is read again
                        Set<Variable<?>> s = data.requiredVariables.get(pt);
                        if(s == null) {
                            data.requiredVariables.put(pt, requiredVariables);
                            requiredVariables = new HashSet<>();
                        } else {
                            s.addAll(requiredVariables);
                            requiredVariables.clear();
                        }
                    }
                    break;
                }
                default: {
                    if(data.passValues) {
                        Variable<?> v = d.task.getOutput();
                        if(v.isIntermediate() && !v.getType().isArray() && !isSampleGeneration(v, compilationCtx))
                            requiredVariables.add(v);
                    }
                    break;
                }
            }
        }

        // Save any remaining variables to be produced at the end of the trace.
        DataflowTask<?> t = traceHandle.peek().task;
        Set<Variable<?>> s = data.requiredVariables.get(t);
        if(s == null)
            data.requiredVariables.put(t, requiredVariables);
        else
            s.addAll(requiredVariables);
    }

    /**
     * Method to get the index scopes, updating the list of fixed at the same time.
     */
    private static Set<ForTask> getRequiredLoops(Variable<?> v) {
        // Construct a set to hold the results.
        Set<ForTask> toReturn = new HashSet<>();

        // Construct a stack to hold the values that need to be processed.
        Stack<Variable<?>> toProcess = new Stack<>();
        // Prime the stack with the index to process.
        toProcess.add(v);

        Set<Variable<?>> seen = new HashSet<>();

        // While there are values to process.
        while(!toProcess.isEmpty()) {
            v = toProcess.pop();
            if(!seen.contains(v)) {
                seen.add(v);
                // If the value is an intermediate get the scopes that will be needed to dereference it.
                if(v.isIntermediate()) {
                    Scope s = v.scope();
                    while(s != GlobalScope.scope) {
                        switch(s.getScopeType()) {
                            case FOR:
                                toReturn.add((ForTask) s);
                                break;
                            default:
                                break;
                        }
                        s = s.getEnclosingScope();
                    }
                } else {
                    // Get the value and recover its constructing dataflow task.
                    DataflowTask<?> d = v.getParent();
                    // Depending on the task type.
                    switch(d.getType()) {
                        case FOR:
                        case PAR_FOR: {
                            // If it is a for task add the for to the list of scopes.
                            ForTask f = (ForTask) d;
                            toReturn.add(f);
                            toProcess.addAll(d.getInputs());
                            break;
                        }
                        case PUT: {
                            PutTask<?> pt = (PutTask<?>) d;
                            toProcess.add(pt.array);
                            break;
                        }
                        case ARRAY_CONSTRUCTOR:
                        case SAMPLE: {
                            // If it is a sample or array constructor stop as the value
                            // will be calculated separately, but add any scopes that
                            // the variable is declared in as these will be needed
                            // to access the instance of the variable.
                            Scope s = d.scope();
                            while(s != GlobalScope.scope) {
                                switch(s.getScopeType()) {
                                    case FOR:
                                        toReturn.add((ForTask) s);
                                        break;
                                    default:
                                        break;
                                }
                                s = s.getEnclosingScope();
                            }
                            break;
                        }
                        case REDUCTION_RETURN: { // Skip over any scopes inside the reduction.
                            ReductionReturnTask<?> rrt = (ReductionReturnTask<?>) d;
                            ReductionScope<?> scope = rrt.getReductionScope();
                            toProcess.add(scope.array);
                            toProcess.add(scope.emptyValue);
                            toProcess.add(scope.start);
                            toProcess.add(scope.end);
                            break;
                        }
                        default: {
                            // For all other operations just add the inputs to the
                            // list of values to process.
                            toProcess.addAll(d.getInputs());
                            break;
                        }
                    }
                }
            }
        }
        return toReturn;
    }

    private static ScopeDescription constructRestrictionInternal(RestrictionsData data, ScopeDescription target,
            CompilationContext compilationCtx) {
        TraceHandle traceHandle = data.trace;

        {
            List<VariablePair<?>> subs = new ArrayList<>();
            for(Entry<Scope, IntVariable> p:data.existingStartScopes.entrySet()) {
                Scope s = p.getKey();
                if(s.getScopeType() == ScopeType.FOR)
                    subs.add(new VariablePair<>(((ForTask) s).getIndex(), p.getValue()));
            }
            if(!subs.isEmpty())
                target = target.addSubstitutions(data.position, subs);
        }

        // A map from dataflow tasks to put task indexes that were calculated earlier.
        Map<DataflowTask<?>, IRTreeReturn<IntVariable>> putIndexes = new HashMap<>();

        // Add an isolating scope to all traces in case scope parameters cause variables to be declared.
        target = target.insertBlockScope(Tree.NoComment, compilationCtx);

        int size = traceHandle.size();
        for(int i = 0; i < size; i++) {
            DataflowTaskArgDesc d = traceHandle.get(i);
            switch(d.task.getType()) {
                case GET: {
                    if(d.argPos == 0) {
                        GetTask<?> gt = (GetTask<?>) d.task;

                        // Construct the environment
                        ScopeChanges s = data.scopeData.get(gt);
                        target = constructEnvironment(s, data, target, compilationCtx);

                        // If there is a put to go with this get a guard will be needed
                        IRTreeReturn<IntVariable> putIndex = putIndexes.get(gt);
                        if(putIndex != null) {
                            // Construct the guard.
                            target.applySubstitutions(data.position, compilationCtx);
                            IRTreeReturn<IntVariable> getIndex = gt.index.getForwardIR(compilationCtx);
                            target.removeSubstitutions(data.position, compilationCtx);
                            target = target.insertIfScope(IRTree.eq(putIndex, getIndex), compilationCtx);
                        }
                    }
                    break;
                }

                case PUT: {
                    PutTask<?> pt = (PutTask<?>) d.task;
                    DataflowTask<?> task = data.usedPuts.get(pt);
                    if(task != null) {
                        // Construct the value of the put index
                        ScopeChanges s = data.scopeData.get(pt);
                        target = constructEnvironment(s, data, target, compilationCtx);

                        if(data.storeSubstitutions.contains(pt))
                            target = target.saveTaskState(data.position, pt);

                        // Construct all the values that the put value will depend on. This is required
                        // in the case that the intermediate also depends on the values being updated,
                        // and so needs to be regenerated to include the substituted values.
                        if(data.passValues) {
                            // Make sure there is only one substitute created for the put task value.

                            PriorityQueue<Variable<?>> p = new PriorityQueue<>(data.requiredVariables.get(pt));
                            while(!p.isEmpty()) {
                                Variable<?> v = p.poll();
                                if(v != pt.value)
                                    target = constructVarSubstitution(v, target, data, compilationCtx);
                            }

                            if(!pt.value.getType().isArray()) {
                                target.applySubstitutions(data.position, compilationCtx);
                                Variable<?> vSub = compilationCtx.getSubstitute(pt.value);
                                // If not a sample or the sample is substituted create a substitution for the value.
                                if(!isSampleGeneration(pt.value, compilationCtx) || vSub != pt.value) {
                                    IRTreeReturn<?> t = vSub.getForwardIR(compilationCtx);
                                    target.removeSubstitutions(data.position, compilationCtx);
                                    target = constructVarSubstitution(task.getOutput(), t, target, data,
                                            compilationCtx);
                                } else
                                    target.removeSubstitutions(data.position, compilationCtx);
                            }
                        }

                        // Construct the index for put task, this will be used in the guards later.
                        target.applySubstitutions(data.position, compilationCtx);
                        IRTreeReturn<IntVariable> putIndex = pt.index.getForwardIR(compilationCtx);
                        target.removeSubstitutions(data.position, compilationCtx);

                        // And construct a description of the index and the value paired with the
                        // corresponding get.
                        putIndexes.put(task, putIndex);
                    } else {
                        // No restrictions are required, but the status of the scopes at the point this
                        // is reached should be recorded.
                        if(data.storeSubstitutions.contains(pt))
                            target = target.saveTaskState(data.position, pt);
                    }
                    break;
                }

                case REDUCE_INPUT: {
                    ReductionInput<?> ri = (ReductionInput<?>) d.task;
                    ScopeChanges s = data.scopeData.get(ri);

                    // Construct the environment
                    target = constructEnvironment(s, data, target, compilationCtx);
                    IRTreeReturn<IntVariable> index = putIndexes.get(ri);
                    if(index != null) {
                        // Check that the put was in the range of the range of the reduction
                        target.applySubstitutions(data.position, compilationCtx);
                        IRTreeReturn<IntVariable> start = ri.start.getForwardIR(compilationCtx);
                        IRTreeReturn<IntVariable> end = ri.end.getForwardIR(compilationCtx);
                        target.removeSubstitutions(data.position, compilationCtx);
                        IRTreeReturn<BooleanVariable> guard = IRTree.and(IRTree.lessThanEqual(start, index),
                                IRTree.lessThan(index, end));

                        target = target.insertIfScope(guard, compilationCtx);
                    } else {
                        // Isolate the reduction just in case. This is probably not required, but will
                        // be removed in optimisation.
                        target = target.insertBlockScope(Tree.NoComment, compilationCtx);
                    }

                    // Process the reduction
                    if(data.passValues) {
                        // if the value is being passed via the array, process the reductions with the put index as a
                        // mask
                        if(d.argPos == 3) {
                            if(data.reductionInputs.contains(ri))
                                throw new SandwoodModelException(
                                        "Multiple values are required to be passed through the same reduced array when "
                                                + "performing operations on the model. This is not supported.",
                                        ri);
                            data.reductionInputs.add(ri);
                            target = processReductionInput(ri, index, target, data, compilationCtx);
                        } else
                            // Otherwise just process the reduction.
                            target = processReductionInput(ri, target, data, compilationCtx);
                    }

                    break;
                }

                case IF_ASSIGNMENT: {
                    IfElseAssignmentTask<?> ifElseAssignmentTask = (IfElseAssignmentTask<?>) d.task;

                    // Construct the environment
                    ScopeChanges s = data.scopeData.get(ifElseAssignmentTask);
                    target = constructEnvironment(s, data, target, compilationCtx);

                    // Construct the guard.
                    switch(d.argPos) {
                        case 0: {
                            break;
                        }

                        case 1:
                        case 2: {
                            target.applySubstitutions(data.position, compilationCtx);
                            IRTreeReturn<BooleanVariable> guard = ifElseAssignmentTask.guard
                                    .getForwardIR(compilationCtx);
                            target.removeSubstitutions(data.position, compilationCtx);
                            Variable<?> v;
                            if(d.argPos == 1)
                                v = ifElseAssignmentTask.ifValue;
                            else {
                                v = ifElseAssignmentTask.elseValue;
                                guard = IRTree.negateBoolean(guard);
                            }

                            target = target.insertIfScope(guard, compilationCtx);

                            if(data.passValues) {
                                target.applySubstitutions(data.position, compilationCtx);
                                IRTreeReturn<?> t = v.getForwardIR(compilationCtx);
                                target.removeSubstitutions(data.position, compilationCtx);
                                target = constructVarSubstitution(ifElseAssignmentTask.getOutput(), t, target, data,
                                        compilationCtx);
                            }
                            break;
                        }

                        default:
                            throw new CompilerException("Unexpected argument position " + d.argPos);
                    }

                    break;
                }

                default:
                    break;
            }
        }

        target = constructAdditionalScopes(data, target, compilationCtx);

        PriorityQueue<Variable<?>> p = new PriorityQueue<>(data.requiredVariables.get(data.trace.peek().task));
        while(!p.isEmpty())
            target = constructVarSubstitution(p.poll(), target, data, compilationCtx);

        return target;
    }

    private static boolean isSampleGeneration(Variable<?> v, CompilationContext compilationCtx) {
        return compilationCtx.getSubstitute(v).getParent().getType() == DFType.SAMPLE;
    }

    private static <A extends Variable<A>> ScopeDescription processReductionInput(ReductionInput<A> ri,
            IRTreeReturn<IntVariable> putIndex, ScopeDescription target, RestrictionsData data,
            CompilationContext compilationCtx) {

        ScopeDescription original = target;

        Variable<A> output = ri.getOutput();
        if(output.getType().isArray())
            throw new MissingFeatureException("Arrays cannot currently be substituted through reductions. This "
                    + "error is being caused because the compiler is trying to declare local variables to avoid altering "
                    + "the model state at this part of the code, but can only do this for scalar values.");
        /*
         * If values are being passed, the reduction of the elements except the one being passed is first constructed,
         * then the passed value is included.
         */

        // For now remove the put task substitution
        target.applySubstitutions(data.position, compilationCtx);
        Variable<A> putValue = compilationCtx.getSubstitute(output);
        compilationCtx.removeSubstitute(output);

        ReductionScope<A> rs = ri.scope();

        // Construct the value from the rest of the array.);
        Variable<A> maskedResult = rs.reduceArrayValue(ri, putIndex, compilationCtx);

        target = target.insertScope(maskedResult.scope(), compilationCtx);

        compilationCtx.addSubstitute(output, putValue);
        original.removeSubstitutions(data.position, compilationCtx);

        compilationCtx.addSubstitute(rs.j, maskedResult);
        compilationCtx.addScopeSubstitute(rs, maskedResult.scope());
        target = constructVarSubstitution(rs.returnVar, target, data, compilationCtx);
        compilationCtx.removeScopeSubstitute(rs);
        compilationCtx.removeSubstitute(rs.j);

        return target;
    }

    private static <A extends Variable<A>> ScopeDescription processReductionInput(ReductionInput<A> ri,
            ScopeDescription target, RestrictionsData data, CompilationContext compilationCtx) {

        ScopeDescription original = target;

        Variable<A> output = ri.getOutput();
        if(output.getType().isArray())
            throw new MissingFeatureException("Arrays cannot currently be substituted through reductions. This "
                    + "error is being caused because the compiler is trying to declare local variables to avoid altering "
                    + "the model state at this part of the code, but can only do this for scalar values.");

        ReductionScope<A> rs = ri.scope();

        // Construct the value from the rest of the array.
        target.applySubstitutions(data.position, compilationCtx);
        Variable<A> maskedResult = rs.reduceEmptyValue(ri, compilationCtx);

        target = target.insertScope(maskedResult.scope(), compilationCtx);
        original.removeSubstitutions(data.position, compilationCtx);

        compilationCtx.addSubstitute(rs.i, rs.emptyValue);
        compilationCtx.addSubstitute(rs.j, maskedResult);
        target = constructVarSubstitution(rs.returnVar, target, data, compilationCtx);
        compilationCtx.removeSubstitute(rs.i);
        compilationCtx.removeSubstitute(rs.j);
        return target;
    }

    /**
     * A function to add a newly constructed variable to the scope that holds the value of the variable constructed in
     * the current state of the compilationCtx, and add a substitution that will replace the provided variable with a
     * load of the newly constructed variable. This allows values to be cached as locally rather than written out to
     * globals where collisions in multithreaded code can occur.
     *
     * @param <A>              The type of the variable
     * @param v                Variable that will be substituted.
     * @param t                Tree providing the value to be used in the substitution
     * @param scope            The scope of the variable should be created in.
     * @param data             The data object providing the context.
     * @param varSubstitutions A set recording all the substitutions made.
     * @param compilationCtx   The compilation context of the function.
     */
    private static <A extends Variable<A>> ScopeDescription constructVarSubstitution(Variable<A> v, IRTreeReturn<?> t,
            ScopeDescription target, RestrictionsData data, CompilationContext compilationCtx) {
        LocalVariableDescription<A> subName = VariableNames.traceTempName(v.getVarDesc().name, data.globalID, data.localID++,
                v.getType());
        IRTreeVoid init = IRTree.initializeVariable(subName, (IRTreeReturn<A>) t, Tree.NoComment);
        target = target.addSubstitution(data.position, v, target.constructVariableInScope(subName));
        target.addTreeToScope(init, compilationCtx);
        return target;
    }

    /**
     * A function to add a newly constructed variable to the scope that holds the value of the variable constructed in
     * the current state of the compilationCtx, and add a substitution that will replace the provided variable with a
     * load of the newly constructed variable. This allows values to be cached as locally rather than written out to
     * globals where collisions in multithreaded code can occur.
     *
     * @param <A>              The type of the variable
     * @param v                Variable that will be substituted.
     * @param scope            The scope of the variable should be created in.
     * @param data             The data object providing the context.
     * @param varSubstitutions A set recording all the substitutions made.
     * @param compilationCtx   The compilation context of the function.
     */
    private static <A extends Variable<A>> ScopeDescription constructVarSubstitution(Variable<A> v,
            ScopeDescription target, RestrictionsData data, CompilationContext compilationCtx) {
        target.applySubstitutions(data.position, compilationCtx);
        v.calculateIntermediate(true);
        IRTreeReturn<A> t = v.getForwardIR(compilationCtx);
        v.calculateIntermediate(false);
        target.removeSubstitutions(data.position, compilationCtx);
        return constructVarSubstitution(v, t, target, data, compilationCtx);
    }

    private static ScopeDescription constructEnvironment(ScopeChanges s, RestrictionsData data,
            ScopeDescription outerScope, CompilationContext compilationCtx) {

        Set<Scope> finalSubstitutionScopes = s.getSubstituteScopes();
        Set<Scope> constructScopes = s.getConstructScopes();

        // Construct any required substitutions for existing Scopes
        if(!finalSubstitutionScopes.isEmpty()) {
            PriorityQueue<Scope> p = new PriorityQueue<>(scopeCmp);
            p.addAll(finalSubstitutionScopes);
            Scope scope = p.peek();
            while(!p.isEmpty()) {
                scope = p.poll();

                // If we have replaced the old scope remove its substitution
                // Add in substitutes for the new scopes
                if(scope.getScopeType() == ScopeType.FOR) {
                    IntVariable index = data.existingEndScopes.get(scope);
                    outerScope = outerScope.addSubstitution(data.position, ((ForTask) scope).getIndex(), index);
                }
            }
            outerScope = outerScope.mergeInInitialized(data.position, data.finalInitializationState, scope);
        }

        // Construct any required Scopes
        if(!constructScopes.isEmpty()) {
            PriorityQueue<Scope> p = new PriorityQueue<>(scopeCmp);
            p.addAll(constructScopes);
            while(!p.isEmpty()) {
                Scope scope = p.poll();

                switch(scope.getScopeType()) {
                    case IF: {
                        IfScope ifScope = (IfScope) scope;
                        outerScope = outerScope.insertIfScope(ifScope.guard, compilationCtx);
                        break;
                    }
                    case ELSE: {
                        ElseScope elseScope = (ElseScope) scope;
                        outerScope = outerScope.insertElseScope(elseScope.ifScope.guard, compilationCtx);
                        break;
                    }
                    case FOR: {
                        ForTask t = (ForTask) scope;
                        outerScope = outerScope.insertForScope(t, data.globalID + "_" + data.localID++, data.position,
                                compilationCtx);
                        break;
                    }
                    case BLOCK: {
                        BlockScope blockScope = (BlockScope) scope;
                        outerScope = outerScope.insertBlockScope(blockScope.comment, compilationCtx);
                        break;
                    }
                    case COMMENT: {
                        CommentScope commentScope = (CommentScope) scope;
                        outerScope = outerScope.insertCommentScope(commentScope.comment, compilationCtx);
                        break;
                    }
                    default:
                        break;
                }
            }
        }
        return outerScope;
    }

    private static ScopeDescription constructAdditionalScopes(RestrictionsData data, ScopeDescription target,
            CompilationContext compilationCtx) {
        for(Scope scope:data.finalScopes) {
            switch(scope.getScopeType()) {
                case IF: {
                    IfScope ifScope = (IfScope) scope;
                    target = target.insertIfScope(ifScope.guard, compilationCtx);
                    break;
                }
                case ELSE: {
                    ElseScope elseScope = (ElseScope) scope;
                    target = target.insertElseScope(elseScope.ifScope.guard, compilationCtx);
                    break;
                }
                case FOR: {
                    ForTask t = (ForTask) scope;
                    target = target.insertForScope(t, data.globalID + "_" + data.localID++, data.position,
                            compilationCtx);
                    break;
                }
                case BLOCK: {
                    BlockScope blockScope = (BlockScope) scope;
                    target = target.insertBlockScope(blockScope.comment, compilationCtx);
                    break;
                }
                case COMMENT: {
                    CommentScope commentScope = (CommentScope) scope;
                    target = target.insertCommentScope(commentScope.comment, compilationCtx);
                    break;
                }
                default:
                    break;
            }
        }

        return target;
    }

    public static boolean restrictionRequired(TraceHandle th) {
        int i = 0;
        int size = th.size();
        while(i < size) {
            DFType type = th.get(i++).task.getType();
            if(type == DFType.PUT)
                break;
            if(type == DFType.IF_ASSIGNMENT)
                return true;
        }

        while(i < size) {
            DFType type = th.get(i++).task.getType();
            if(type == DFType.GET)
                return true;
            if(type == DFType.IF_ASSIGNMENT)
                return true;
        }

        return false;
    }
}
