package macaron;

interface BuildCheck$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public boolean get$deploy_action();
	public void set$deploy_action(boolean calculationVariable$value);
	public boolean get$deploy_action_certainty();
	public void set$deploy_action_certainty(boolean calculationVariable$value);
	public boolean get$deploy_command();
	public void set$deploy_command(boolean calculationVariable$value);
	public boolean get$deploy_command_certainty();
	public void set$deploy_command_certainty(boolean calculationVariable$value);
	public boolean get$deploy_kws();
	public void set$deploy_kws(boolean calculationVariable$value);
	public boolean get$deploy_kws_certainty();
	public void set$deploy_kws_certainty(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample10();
	public void set$fixedFlag$sample10(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample12();
	public void set$fixedFlag$sample12(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample14();
	public void set$fixedFlag$sample14(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample16();
	public void set$fixedFlag$sample16(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample21();
	public void set$fixedFlag$sample21(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample28();
	public void set$fixedFlag$sample28(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample36();
	public void set$fixedFlag$sample36(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample44();
	public void set$fixedFlag$sample44(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample49();
	public void set$fixedFlag$sample49(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample51();
	public void set$fixedFlag$sample51(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample53();
	public void set$fixedFlag$sample53(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample58();
	public void set$fixedFlag$sample58(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample65();
	public void set$fixedFlag$sample65(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample73();
	public void set$fixedFlag$sample73(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample78();
	public void set$fixedFlag$sample78(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample83();
	public void set$fixedFlag$sample83(boolean calculationVariable$value);
	public double get$logProbability$deploy_action();
	public double get$logProbability$deploy_action_certainty();
	public double get$logProbability$deploy_command();
	public double get$logProbability$deploy_command_certainty();
	public double get$logProbability$deploy_kws();
	public double get$logProbability$deploy_kws_certainty();
	public double get$logProbability$release_workflow_trigger_deploy_action();
	public double get$logProbability$release_workflow_trigger_deploy_command();
	public double get$logProbability$step_uses_secrets_deploy_action();
	public double get$logProbability$step_uses_secrets_deploy_command();
	public double get$logProbability$tested_deploy_action();
	public double get$p_deploy_action();
	public void set$p_deploy_action(double calculationVariable$value);
	public double get$p_deploy_command();
	public void set$p_deploy_command(double calculationVariable$value);
	public double get$p_deploy_kws();
	public void set$p_deploy_kws(double calculationVariable$value);
	public double get$p_release_workflow_trigger_deploy_action();
	public void set$p_release_workflow_trigger_deploy_action(double calculationVariable$value);
	public double get$p_release_workflow_trigger_deploy_command();
	public void set$p_release_workflow_trigger_deploy_command(double calculationVariable$value);
	public double get$p_step_uses_secrets_deploy_action();
	public void set$p_step_uses_secrets_deploy_action(double calculationVariable$value);
	public double get$p_step_uses_secrets_deploy_command();
	public void set$p_step_uses_secrets_deploy_command(double calculationVariable$value);
	public double get$p_tested_deploy_action();
	public void set$p_tested_deploy_action(double calculationVariable$value);
	public boolean get$release_workflow_trigger_deploy_action();
	public void set$release_workflow_trigger_deploy_action(boolean calculationVariable$value);
	public boolean get$release_workflow_trigger_deploy_command();
	public void set$release_workflow_trigger_deploy_command(boolean calculationVariable$value);
	public boolean get$step_uses_secrets_deploy_action();
	public void set$step_uses_secrets_deploy_action(boolean calculationVariable$value);
	public boolean get$step_uses_secrets_deploy_command();
	public void set$step_uses_secrets_deploy_command(boolean calculationVariable$value);
	public boolean get$tested_deploy_action();
	public void set$tested_deploy_action(boolean calculationVariable$value);
	public void logEvidenceGeneration();
}