package org.sandwood.compiler.tests.parser;

interface NoisyOr$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public boolean get$fixedFlag$sample12();
	public void set$fixedFlag$sample12(boolean cv$value);
	public boolean get$fixedFlag$sample15();
	public void set$fixedFlag$sample15(boolean cv$value);
	public boolean get$fixedFlag$sample18();
	public void set$fixedFlag$sample18(boolean cv$value);
	public boolean get$fixedFlag$sample233();
	public void set$fixedFlag$sample233(boolean cv$value);
	public boolean get$fixedFlag$sample248();
	public void set$fixedFlag$sample248(boolean cv$value);
	public boolean get$fixedFlag$sample263();
	public void set$fixedFlag$sample263(boolean cv$value);
	public boolean get$fixedFlag$sample278();
	public void set$fixedFlag$sample278(boolean cv$value);
	public boolean get$fixedFlag$sample293();
	public void set$fixedFlag$sample293(boolean cv$value);
	public boolean get$fixedFlag$sample3();
	public void set$fixedFlag$sample3(boolean cv$value);
	public boolean get$fixedFlag$sample308();
	public void set$fixedFlag$sample308(boolean cv$value);
	public boolean get$fixedFlag$sample430();
	public void set$fixedFlag$sample430(boolean cv$value);
	public boolean get$fixedFlag$sample6();
	public void set$fixedFlag$sample6(boolean cv$value);
	public boolean get$fixedFlag$sample9();
	public void set$fixedFlag$sample9(boolean cv$value);
	public boolean get$flag1();
	public void set$flag1(boolean cv$value);
	public boolean get$flag2();
	public void set$flag2(boolean cv$value);
	public boolean get$flag3();
	public void set$flag3(boolean cv$value);
	public boolean get$flag4();
	public void set$flag4(boolean cv$value);
	public boolean get$flag5();
	public void set$flag5(boolean cv$value);
	public boolean get$flag6();
	public void set$flag6(boolean cv$value);
	public boolean[][] get$issues$var213();
	public void set$issues$var213(boolean[][] cv$value);
	public boolean[][] get$issues$var383();
	public void set$issues$var383(boolean[][] cv$value);
	public double get$logProbability$flag1();
	public double get$logProbability$flag2();
	public double get$logProbability$flag3();
	public double get$logProbability$flag4();
	public double get$logProbability$flag5();
	public double get$logProbability$flag6();
	public double get$logProbability$n13State();
	public double get$logProbability$noisyOr();
	public boolean[] get$n13State();
	public boolean[] get$noisyOr();
	public double[][] get$p();
	public double[][] get$p13();
	public double get$prior1();
	public double get$prior2();
	public double get$prior3();
	public double get$prior4();
	public double get$prior5();
	public double get$prior6();
}