package org.sandwood.compiler.tests.parser;

interface HMM_Mk2Dist$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public double[][] get$bias();
	public void set$bias(double[][] cv$value);
	public double[][][] get$distribution$sample126();
	public void set$distribution$sample126(double[][][] cv$value);
	public double[][] get$distribution$sample95();
	public void set$distribution$sample95(double[][] cv$value);
	public int[][] get$events();
	public int[][] get$eventsMeasured();
	public void set$eventsMeasured(int[][] cv$value);
	public boolean get$fixedFlag$sample126();
	public void set$fixedFlag$sample126(boolean cv$value);
	public boolean get$fixedFlag$sample42();
	public void set$fixedFlag$sample42(boolean cv$value);
	public boolean get$fixedFlag$sample57();
	public void set$fixedFlag$sample57(boolean cv$value);
	public boolean get$fixedFlag$sample78();
	public void set$fixedFlag$sample78(boolean cv$value);
	public boolean get$fixedFlag$sample80();
	public void set$fixedFlag$sample80(boolean cv$value);
	public boolean get$fixedFlag$sample95();
	public void set$fixedFlag$sample95(boolean cv$value);
	public int get$initialState();
	public void set$initialState(int cv$value);
	public int[] get$length$eventsMeasured();
	public void set$length$eventsMeasured(int[] cv$value);
	public double get$logProbability$bias();
	public double get$logProbability$events();
	public double get$logProbability$initialState();
	public double get$logProbability$m();
	public double get$logProbability$st();
	public double get$logProbability$weights();
	public double[][] get$m();
	public void set$m(double[][] cv$value);
	public int get$noEvents();
	public void set$noEvents(int cv$value);
	public int get$noStates();
	public void set$noStates(int cv$value);
	public int get$samples();
	public int[][] get$st();
	public void set$st(int[][] cv$value);
	public double[] get$v();
	public double[] get$v2();
	public double[] get$weights();
	public void set$weights(double[] cv$value);
	public void logEvidenceGeneration();
}