package org.sandwood.compiler.tests.parser;

import org.sandwood.runtime.internal.model.CoreModel;

interface HMMMetrics$CoreInterface extends CoreModel {
	public double[] get$cpu();
	public double[] get$cpuMean();
	public void set$cpuMean(double[] cv$value, boolean allocated$);
	public double[] get$cpuVar();
	public void set$cpuVar(double[] cv$value, boolean allocated$);
	public double[] get$cpu_measured();
	public void set$cpu_measured(double[] cv$value, boolean allocated$);
	public double[] get$distribution$sample39();
	public void set$distribution$sample39(double[] cv$value, boolean allocated$);
	public double[][] get$distribution$sample57();
	public void set$distribution$sample57(double[][] cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample113();
	public void set$fixedFlag$sample113(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample130();
	public void set$fixedFlag$sample130(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample147();
	public void set$fixedFlag$sample147(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample164();
	public void set$fixedFlag$sample164(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample30();
	public void set$fixedFlag$sample30(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample36();
	public void set$fixedFlag$sample36(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample39();
	public void set$fixedFlag$sample39(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample57();
	public void set$fixedFlag$sample57(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample77();
	public void set$fixedFlag$sample77(boolean cv$value, boolean allocated$);
	public boolean get$fixedFlag$sample95();
	public void set$fixedFlag$sample95(boolean cv$value, boolean allocated$);
	public double[] get$initialStateDistribution();
	public void set$initialStateDistribution(double[] cv$value, boolean allocated$);
	public int get$length$cpu_measured();
	public void set$length$cpu_measured(int cv$value, boolean allocated$);
	public double get$logProbability$cpu();
	public double get$logProbability$cpuMean();
	public double get$logProbability$cpuVar();
	public double get$logProbability$initialStateDistribution();
	public double get$logProbability$m();
	public double get$logProbability$mem();
	public double get$logProbability$memMean();
	public double get$logProbability$memVar();
	public double get$logProbability$pageFaults();
	public double get$logProbability$pageFaultsMean();
	public double get$logProbability$pageFaultsVar();
	public double get$logProbability$st();
	public double[][] get$m();
	public void set$m(double[][] cv$value, boolean allocated$);
	public double[] get$mem();
	public double[] get$memMean();
	public void set$memMean(double[] cv$value, boolean allocated$);
	public double[] get$memVar();
	public void set$memVar(double[] cv$value, boolean allocated$);
	public double[] get$mem_measured();
	public void set$mem_measured(double[] cv$value, boolean allocated$);
	public int get$noStates();
	public void set$noStates(int cv$value, boolean allocated$);
	public double[] get$pageFaults();
	public double[] get$pageFaultsMean();
	public void set$pageFaultsMean(double[] cv$value, boolean allocated$);
	public double[] get$pageFaultsVar();
	public void set$pageFaultsVar(double[] cv$value, boolean allocated$);
	public double[] get$pageFaults_measured();
	public void set$pageFaults_measured(double[] cv$value, boolean allocated$);
	public int get$samples();
	public int[] get$st();
	public void set$st(int[] cv$value, boolean allocated$);
	public double[] get$v();
}