package org.sandwood.compiler.tests.parser;

interface HMMMetrics$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public double[] get$cpu();
	public void set$cpu(double[] cv$value);
	public double[] get$cpuMean();
	public void set$cpuMean(double[] cv$value);
	public double[] get$cpuVar();
	public void set$cpuVar(double[] cv$value);
	public double[] get$cpu_measured();
	public void set$cpu_measured(double[] cv$value);
	public boolean get$fixedFlag$sample100();
	public void set$fixedFlag$sample100(boolean cv$value);
	public boolean get$fixedFlag$sample110();
	public void set$fixedFlag$sample110(boolean cv$value);
	public boolean get$fixedFlag$sample119();
	public void set$fixedFlag$sample119(boolean cv$value);
	public boolean get$fixedFlag$sample124();
	public void set$fixedFlag$sample124(boolean cv$value);
	public boolean get$fixedFlag$sample129();
	public void set$fixedFlag$sample129(boolean cv$value);
	public boolean get$fixedFlag$sample25();
	public void set$fixedFlag$sample25(boolean cv$value);
	public boolean get$fixedFlag$sample32();
	public void set$fixedFlag$sample32(boolean cv$value);
	public boolean get$fixedFlag$sample35();
	public void set$fixedFlag$sample35(boolean cv$value);
	public boolean get$fixedFlag$sample45();
	public void set$fixedFlag$sample45(boolean cv$value);
	public boolean get$fixedFlag$sample58();
	public void set$fixedFlag$sample58(boolean cv$value);
	public boolean get$fixedFlag$sample69();
	public void set$fixedFlag$sample69(boolean cv$value);
	public boolean get$fixedFlag$sample80();
	public void set$fixedFlag$sample80(boolean cv$value);
	public boolean get$fixedFlag$sample90();
	public void set$fixedFlag$sample90(boolean cv$value);
	public double[] get$initialStateDistribution();
	public void set$initialStateDistribution(double[] cv$value);
	public int get$length$cpu_measured();
	public void set$length$cpu_measured(int cv$value);
	public double get$logProbability$cpu();
	public double get$logProbability$cpuMean();
	public double get$logProbability$cpuVar();
	public double get$logProbability$initialStateDistribution();
	public double get$logProbability$m();
	public double get$logProbability$mem();
	public double get$logProbability$memMean();
	public double get$logProbability$memVar();
	public double get$logProbability$pageFaults();
	public double get$logProbability$pageFaultsMean();
	public double get$logProbability$pageFaultsVar();
	public double get$logProbability$st();
	public double[][] get$m();
	public void set$m(double[][] cv$value);
	public double[] get$mem();
	public void set$mem(double[] cv$value);
	public double[] get$memMean();
	public void set$memMean(double[] cv$value);
	public double[] get$memVar();
	public void set$memVar(double[] cv$value);
	public double[] get$mem_measured();
	public void set$mem_measured(double[] cv$value);
	public int get$noStates();
	public void set$noStates(int cv$value);
	public double[] get$pageFaults();
	public void set$pageFaults(double[] cv$value);
	public double[] get$pageFaultsMean();
	public void set$pageFaultsMean(double[] cv$value);
	public double[] get$pageFaultsVar();
	public void set$pageFaultsVar(double[] cv$value);
	public double[] get$pageFaults_measured();
	public void set$pageFaults_measured(double[] cv$value);
	public int get$samples();
	public int[] get$st();
	public void set$st(int[] cv$value);
	public double[] get$v();
	public void logEvidenceGeneration();
}