package macaron;

interface BuildCheck3$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public boolean get$deploy_action();
	public void set$deploy_action(boolean calculationVariable$value);
	public boolean get$deploy_action_certainty();
	public void set$deploy_action_certainty(boolean calculationVariable$value);
	public boolean get$deploy_command();
	public void set$deploy_command(boolean calculationVariable$value);
	public boolean get$deploy_command_certainty();
	public void set$deploy_command_certainty(boolean calculationVariable$value);
	public boolean get$deploy_kws();
	public void set$deploy_kws(boolean calculationVariable$value);
	public boolean get$deploy_kws_certainty();
	public void set$deploy_kws_certainty(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample46();
	public void set$fixedFlag$sample46(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample48();
	public void set$fixedFlag$sample48(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample51();
	public void set$fixedFlag$sample51(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample54();
	public void set$fixedFlag$sample54(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample84();
	public void set$fixedFlag$sample84(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample86();
	public void set$fixedFlag$sample86(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample89();
	public void set$fixedFlag$sample89(boolean calculationVariable$value);
	public boolean get$fixedFlag$sample99();
	public void set$fixedFlag$sample99(boolean calculationVariable$value);
	public boolean get$invalid_trigger();
	public void set$invalid_trigger(boolean calculationVariable$value);
	public double get$logProbability$deploy_action_certainty();
	public double get$logProbability$deploy_command_certainty();
	public double get$logProbability$deploy_kws_certainty();
	public double get$p_deploy_action();
	public double get$p_deploy_command();
	public double get$p_deploy_kws();
	public double get$p_release_workflow_trigger_deploy_action();
	public double get$p_release_workflow_trigger_deploy_command();
	public double get$p_step_uses_secrets_deploy_action();
	public double get$p_step_uses_secrets_deploy_command();
	public double get$p_tested_deploy_action();
	public boolean get$release_workflow_trigger_deploy_action();
	public void set$release_workflow_trigger_deploy_action(boolean calculationVariable$value);
	public boolean get$release_workflow_trigger_deploy_command();
	public void set$release_workflow_trigger_deploy_command(boolean calculationVariable$value);
	public boolean get$step_uses_secrets_deploy_action();
	public void set$step_uses_secrets_deploy_action(boolean calculationVariable$value);
	public boolean get$step_uses_secrets_deploy_command();
	public void set$step_uses_secrets_deploy_command(boolean calculationVariable$value);
	public boolean get$tested_deploy_action();
	public void set$tested_deploy_action(boolean calculationVariable$value);
	public void logEvidenceGeneration();
}