package org.sandwood.compiler.tests.parser;

interface HMMMetrics2$CoreInterface extends org.sandwood.runtime.internal.model.CoreModel {
	public boolean get$fixedFlag$sample117();
	public void set$fixedFlag$sample117(boolean cv$value);
	public boolean get$fixedFlag$sample136();
	public void set$fixedFlag$sample136(boolean cv$value);
	public boolean get$fixedFlag$sample158();
	public void set$fixedFlag$sample158(boolean cv$value);
	public boolean get$fixedFlag$sample170();
	public void set$fixedFlag$sample170(boolean cv$value);
	public boolean get$fixedFlag$sample30();
	public void set$fixedFlag$sample30(boolean cv$value);
	public boolean get$fixedFlag$sample43();
	public void set$fixedFlag$sample43(boolean cv$value);
	public boolean get$fixedFlag$sample63();
	public void set$fixedFlag$sample63(boolean cv$value);
	public boolean get$fixedFlag$sample79();
	public void set$fixedFlag$sample79(boolean cv$value);
	public boolean get$fixedFlag$sample95();
	public void set$fixedFlag$sample95(boolean cv$value);
	public double[] get$initialStateDistribution();
	public void set$initialStateDistribution(double[] cv$value);
	public int[] get$length$metric();
	public void set$length$metric(int[] cv$value);
	public double get$logProbability$initialStateDistribution();
	public double get$logProbability$m();
	public double get$logProbability$metric_g();
	public double get$logProbability$metric_mean();
	public double get$logProbability$metric_valid_bias();
	public double get$logProbability$metric_valid_g();
	public double get$logProbability$metric_var();
	public double get$logProbability$st();
	public double[][] get$m();
	public void set$m(double[][] cv$value);
	public double[][] get$metric();
	public void set$metric(double[][] cv$value);
	public double[][] get$metric_g();
	public void set$metric_g(double[][] cv$value);
	public double[] get$metric_mean();
	public void set$metric_mean(double[] cv$value);
	public boolean[][] get$metric_valid();
	public void set$metric_valid(boolean[][] cv$value);
	public double[] get$metric_valid_bias();
	public void set$metric_valid_bias(double[] cv$value);
	public boolean[][] get$metric_valid_g();
	public void set$metric_valid_g(boolean[][] cv$value);
	public double[] get$metric_var();
	public void set$metric_var(double[] cv$value);
	public int get$noSamples();
	public int get$noStates();
	public void set$noStates(int cv$value);
	public int[][] get$st();
	public void set$st(int[][] cv$value);
	public double[] get$v();
	public void logEvidenceGeneration();
}